##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## make a file
##

SRC	=	my_compute_power_rec.c \
		my_compute_square_root.c \
		my_find_prime_sup.c \
		my_getnbr.c \
		my_isneg.c \
		my_is_prime.c \
		my_putchar.c \
		my_putchar_error.c \
		my_put_nbr.c \
		my_putstr.c \
		my_putstr_error.c \
		my_revstr.c \
		my_showmem.c \
		my_showstr.c \
		my_show_word_array.c \
		my_sort_int_array.c \
		my_strcapitalize.c \
		my_strcat.c \
		my_strcmp.c \
		my_strcpy.c \
		my_strdup.c \
		my_str_isalpha.c \
		my_str_islower.c \
		my_str_isnum.c \
		my_str_isprintable.c \
		my_str_isupper.c \
		my_strlen.c \
		my_strlen_without_space.c \
		my_strlowcase.c \
		my_strncat.c \
		my_strncmp.c \
		my_strncpy.c \
		my_strstr.c \
		my_strupcase.c \
		my_swap.c \
		my_doop_getnbr.c \
		my_strlen_without_signe.c \
		my_int_compare.c \
		my_strcmp_add.c \
		my_is_pos.c \
		my_alloc_char.c \
		my_nbrcmp.c \
		my_strswap.c \
		my_str_extract.c \
		my_intlen.c \
		my_is_pos_getnbr.c

OBJ	=	$(SRC:.c=.o)

NAME = libmy.a

all:	$(NAME)

$(NAME):	$(OBJ)
	ar rc $(NAME) $(OBJ)
	cp $(NAME) ../
	cp my.h ../../include

clean:
	rm -rf *.o

fclean: clean
	rm $(NAME)
	rm ../$(NAME)

re: fclean all
